### ISSUE TITLE
Icon Request: Kubernetes

### ISSUE THREAD

**Issue by donaldguy** [vorillaz/devicons#114]
official SVG (albeit currently blue) and PDF here: https://github.com/kubernetes/kubernetes/tree/master/logo

With the GCE and OpenShift and Docker logos, its a pretty noticeable absence

In particular, I am in want of it for the sake of adorning a [bhilburn/powerlevel9k](https://github.com/bhilburn/powerlevel9k) segment to display the output of `kubectl config current-context`

**Comment by zikes** [comment]
Wow, I wound up here to ask for the same thing for the same reason. This set hasn't been updated in a couple years, I guess a different icon set would be more suitable.

**Comment by jmthvt** [comment]
Bump!
