### ISSUE TITLE
FSharp's new logo

### ISSUE THREAD

**Issue by khellang** [vorillaz/devicons#47]
F# recently got their new logo. It would be awesome to have it included in the set :wink:

See http://fsharp.org/foundation/logo.html

![](http://fsharp.org/img/logo/fsharp512.png)

**Comment by vorillaz** [comment]
#F's new logo is packed into version 1.7.0.
Happy new year and thanks for the support.
http://vorillaz.github.io/devicons/#/singleicon/fsharp
