### ISSUE TITLE
Icon Request: Meteor.js

### ISSUE THREAD

**Issue by aaronagray** [vorillaz/devicons#56]
Thanks for making such an awesome resource! It would be fantastic if [Meteor.js logo](https://d14jjfgstdxsoz.cloudfront.net/meteor-logo.png) makes it into a release. It'd be great to use the icon and / or wordmark, but either would be awesome.

**Comment by vorillaz** [comment]
You may get 2 new Meteor icons packed into version 1.7.0. 
Happy new Year

**Comment by aaronagray** [comment]
Yay! :D
