### ISSUE TITLE
Icon Request: Erlang

### ISSUE THREAD

**Issue by donderom** [vorillaz/devicons#58]
The only icon I miss much is for Erlang as seen in the corner on [erlang.org](http://www.erlang.org/). Also [PNG](http://upload.wikimedia.org/wikipedia/commons/4/42/Erlang_logo.png) and [SVG](http://telegraphics.com.au/~toby/erlang-logo.svg).

Thanks a lot for such an awesome font! :+1:

**Comment by vorillaz** [comment]
Erlang was pushed into version 1.8.0
http://vorillaz.github.io/devicons/#/singleicon/erlang
Thanks for your kind words :)

**Comment by donderom** [comment]
Thanks a lot :+1:
