### ISSUE TITLE
Icon Request: D

### ISSUE THREAD

**Issue by dan-c-underwood** [vorillaz/devicons#59]
As seen here: http://dlang.org

Thanks for an awesome icon set!

**Comment by luke5542** [comment]
The [main logo](http://dlang.org/images/dlogo.svg) on that page is an SVG, which should make adding it easier.

**Comment by vorillaz** [comment]
D language was pushed into version 1.8.0

http://vorillaz.github.io/devicons/#/singleicon/dlang
