### ISSUE TITLE
Legal question

### ISSUE THREAD

**Issue by StachuDotNet** [vorillaz/devicons#60]
I am not a lawyer. Just a dumb dev, so asking this question!
Is there any legal constraint in me taking the .svg font here and porting them to https://github.com/maxogden/hexbin?

**Comment by Alhadis** [comment]
This project is released under the MIT license, which permits work to be distributed in modified or unmodified form, as long as author attribution is given. That is, as long as you're not pretending to be the one who created all those icons.
