### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by stfnhrrs** [vorillaz/devicons#61]
It would be great if you could add some more hosting providers like AWS, RackSpace etc.. and an Apache icon.

**Comment by vorillaz** [comment]
AWS, Rackspace, Google cloud platform, Open Shift and Digital Ocean were pushed into version 1.8.0

http://vorillaz.github.io/devicons/#/singleicon/aws
http://vorillaz.github.io/devicons/#/singleicon/rackspace
http://vorillaz.github.io/devicons/#/singleicon/openshift
http://vorillaz.github.io/devicons/#/singleicon/digital-ocean
