### ISSUE TITLE
icons showing up as black squares for Chrome

### ISSUE THREAD

**Issue by TakaGoto** [vorillaz/devicons#64]
it seems like a problem on my end but it's only working on safari for me. on Chrome I see a black box and in Firefox I see a box with e608 printed.

**Comment by vorillaz** [comment]
Do you use Devicons on a webserver?

**Comment by vorillaz** [comment]
Take a look at how IcoMoon suggests serving an icon font as sometimes you have to use a webserver due to CORS issues.
https://icomoon.io/#docs/importing
 Also try using you may use deliverjs CDN to serve the whole iconset http://www.jsdelivr.com/#!devicons

**Comment by davemachado** [comment]
After messing around with this same issue for a while, I realized that the class value was messed up. All the tutorials available suggest `<i class="devicons-postgresql"></i>`, when in reality you need to call the entire class first, so the correct tag is `<i class="devicons devicons-postgresql"></i>`. Works perfectly after that. Thanks for an awesome project!

**Comment by davemachado** [comment]
The correct CSS class value can be found on the official [cheatsheet].(http://vorillaz.github.io/devicons/#/cheat)

**Comment by suxiaogang** [comment]
@davemachado I still have this issue, even icons in the official cheatsheet page did not render correctly in Chrome 69.

![image](https://user-images.githubusercontent.com/1567518/45616451-1daac800-baa2-11e8-891b-d71906271865.png)

while in Safari:
![image](https://user-images.githubusercontent.com/1567518/45616491-34511f00-baa2-11e8-94d5-58df4d004203.png)

**Comment by suxiaogang** [comment]
@davemachado any clues here?

**Comment by vorillaz** [comment]
@suxiaogang I think it depends on how Chrome 69 renders the font, have you tried tweaking the width of the container?

**Comment by suxiaogang** [comment]
@vorillaz  wow, got you the author !!! Please check the cheatsheet page with Chrome 69 and, ask again, WHY NOT add or merge the new fonts pull request ? We do need them since this repo is updated 3 years ago.

**Comment by vorillaz** [comment]
@suxiaogang You are totally right. I'll check them again and merge the open PRs in order to close the v1 lifecycle of the repo. Just give me a couple of days.
