### ISSUE TITLE
Icon Request : MaterializeCss, SQlite, Vim, ...

### ISSUE THREAD

**Issue by tobeportable** [vorillaz/devicons#65]
http://materializecss.com/res/materialize.svg
![materialize css](http://materializecss.com/res/materialize.svg) 
http://upload.wikimedia.org/wikipedia/commons/3/38/SQLite370.svg
![sqlite db](http://upload.wikimedia.org/wikipedia/commons/3/38/SQLite370.svg)
http://upload.wikimedia.org/wikipedia/commons/9/9f/Vimlogo.svg
![vim editor](http://upload.wikimedia.org/wikipedia/commons/9/9f/Vimlogo.svg)
http://upload.wikimedia.org/wikipedia/en/e/e4/Asterisk_Logo.svg
![asterisk pbx](http://upload.wikimedia.org/wikipedia/en/e/e4/Asterisk_Logo.svg)

**Comment by vorillaz** [comment]
Thanks for the suggestions. I will push the icons soon.

**Comment by vorillaz** [comment]
Version 1.8.0 comes packed with:
Asterisk: http://vorillaz.github.io/devicons/#/singleicon/asterisk
Vim: http://vorillaz.github.io/devicons/#/singleicon/vim
Materialize: http://vorillaz.github.io/devicons/#/singleicon/materializecss
SQLlite: http://vorillaz.github.io/devicons/#/singleicon/sqllite
