### ISSUE TITLE
Icon Request: Neo4J - IntelliJ - Grails - Photoshop

### ISSUE THREAD

**Issue by camilleblondie** [vorillaz/devicons#66]
https://github.com/neo4j-contrib/neo4j-org/blob/master/public/assets/img/neo4j/logo.svg

http://fiji.sc/_images/1/1b/Intellij-idea.png

https://github.com/grails/grails-core/blob/master/media/logos/grails-color-logo.svg

http://upload.wikimedia.org/wikipedia/commons/9/92/Adobe_Photoshop_CS6_icon.svg

**Comment by vorillaz** [comment]
Nice suggestions. I had in mind pushing the PS logo. I will also include the suggested icons in the next release. Thanks for the interest :)

**Comment by vorillaz** [comment]
Version 1.8.0 comes packed with:
IntelliJ IDEA : http://vorillaz.github.io/devicons/#/singleicon/intellij
Grails: http://vorillaz.github.io/devicons/#/singleicon/grails
Photoshop: http://vorillaz.github.io/devicons/#/singleicon/photoshop

Thanks for the support.
