### ISSUE TITLE
Icon Request: scriptcs

### ISSUE THREAD

**Issue by khellang** [vorillaz/devicons#68]
We'd :heart: to have scriptcs included in the set! The full logo is probably a bit big:

![scriptcs logo full](http://cdn.slidesharecdn.com/ss_thumbnails/scriptcs-130613075310-phpapp01-thumbnail-4.jpg?cb=1371331138)

So what about something like my stikers?

![scriptcs logo](https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/2292/large/1414169370/scriptcs.png)

**Comment by adamralph** [comment]
+:100:

**Comment by vorillaz** [comment]
I have started the next version, would you mind delivering a vector version of your logo?

**Comment by adamralph** [comment]
@glennblock @filipw @jrusbatch do any of you have the original vector files?

**Comment by vorillaz** [comment]
ScriptCS added into version 1.8.0
http://vorillaz.github.io/devicons/#/singleicon/scriptcs
Cheers :)
