### ISSUE TITLE
Bower install 1.8 lead to 1.7

### ISSUE THREAD

**Issue by andrkrn** [vorillaz/devicons#70]
http://cdn.jsdelivr.net/devicons/1.8.0/css/devicons.min.css

Devicons 1.7.0 made by Theodore Vorillas / http://vorillaz.com

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
