### ISSUE TITLE
React Icon Does Not WORK!

### ISSUE THREAD

**Issue by kennetpostigo** [vorillaz/devicons#83]
Hey, the react icon is not showing when I place it on a website, If you guys at Devicons could fix it I would really appreciate it. (sorry if the issue title is annoying, was trying to make it visible.)

Thank you!

**Comment by vorillaz** [comment]
Hello there, as I have stated on issue #84 I will need some more infos. Are there any other fonts working? Do you use the CDN option to fetch the font or a local instance?

**Comment by kennetpostigo** [comment]
I use Bower to and get a local instance.

**Comment by KarlPurk** [comment]
I'm also having the same issue with the CDN and npm.  

For example, with the CDN, even though the URL suggests 1.8.0:
http://cdn.jsdelivr.net/devicons/1.8.0/css/devicons.min.css

Inspecting the source shows that it is actually 1.7.0:
>  Devicons 1.7.0 made by Theodore Vorillas / http://vorillaz.com 

The same is true for the npm version.

**Comment by tchret** [comment]
+1
