### ISSUE TITLE
Docker font Icon NOT WORKING!

### ISSUE THREAD

**Issue by kennetpostigo** [vorillaz/devicons#84]
Hey the devicons Docker font is not working. Please fi it when you can.

Thank you.

**Comment by vorillaz** [comment]
Can you please be more specific? Are you trying to use Devicons as a web font? What browser and OS are you using?
Can you spot the icon on the demo website?
http://vorillaz.github.io/devicons/#/singleicon/docker

**Comment by kennetpostigo** [comment]
Im using Devicons as a web font, I am using google chrome, and OS X. Also using bower.

**Comment by brucellino** [comment]
Hi there.

I would like to report that this icon is also not working for me. I'm using cdn.jsdelivr.net/devicons/1.8.0/css/devicons.min.css in my html headers. Other icons are showing (e.g. `devicons-github`), but docker is not. The icons does show up on the web page in [the link](http://vorillaz.github.io/devicons/#/singleicon/docker) referred to above shows fine - just not on my site. 

I'm working locally with a jekyll installation, so unfortunately, I can't send a public demo link.
